# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 66462bf2844aef244fb246058c76ee4c32055e8cdcafa1e077ecdd8a95cf8d4a404d03e850dad0690600be366070891fb8d5c79eeec547fec280edc4143f8b2f

test:
  secret_key_base: 9fbe277c1c02510fcccede997b9a9007a84fd5dc9a0c46efc7f9bf1478e723c31394f8db92c1b095f8ccc9542e07d3a16c0c1d123df7a06dc37c583ccec7690a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
